[package]
name = "asset-hub"
version = "1.17.0"
description = "NAS 资产库索引与管理中枢"
authors = ["you"]
edition = "2021"

[lib]
name = "asset_hub_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ignore = "0.4"
image = { version = "0.25", features = ["exr"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = [
  "implement",
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_System_Com",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_Memory",
  "Win32_System_Ole",
  "Win32_System_SystemServices",
  "Win32_UI_Shell",
] }
